spring:
  data:
    mongodb:
      uri: mongodb://lcl:1234@mongo1:27017,mongo2:27018,mongo3:27019/test?replicaSet=eReplicaSet&authSource=admin
      authentication-database: admin


jwt:
  secret: honyanyaynaynaynaynaringaringaringa
  expiration: 86400000