spring:
  data:
    mongodb:
      uri: mongodb://lcl:1234@mongo1:27017,mongo2:27018,mongo3:27019/test?replicaSet=eReplicaSet&authSource=admin
      authentication-database: admin


jwt:
  secret: honyanyaynaynaynaynaringaringaringa
  expiration: 86400000

iamport:
  api-key: 0713949642152998
  api-secret: 4e6d503ac4e0c8ac8095420d7dcb5ebd82f3c2e106551f600fca3f1ca7d4aab9b31da2cf364d6603